[font]
normal = { family = "Agave Nerd Font", style = "Regular" }

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "D", mods = "Control", action = "ResetFontSize" }
]

[mouse]
hide_when_typing = true
