[font]
normal = { family = "Agave Nerd Font", style = "Regular" }

[colors.normal]
# this fixes colors in ls for directories on my monitor
blue = "#1381a5"

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Enter", mods = "Control", action = "ResetFontSize" }
]

[mouse]
hide_when_typing = true
